version: "3"
services:
  app:
    build: .
    command: bash -c "ruby main.rb -o 0.0.0.0"
    ports:
      - "4567:4567"
    volumes:
      - ./:/app
    depends_on:
      - db
  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sinatra_training_db
